$(function(){
	$('#grid').datagrid({
		url:'report_orderReport',
		columns:[[
		          {field:'name',title:'商品类型',width:100},
		          {field:'y',title:'销售额',width:100}
        ]],
        singleSelect:true,
        onLoadSuccess:function(data){
        	//当表格数据加载成功时，进行画图
        	showChart(data.rows);
        }
	})
	$('#btnSearch').bind('click',function(){
		var formdata=$('#searchForm').serializeJSON();
		if(formdata.endDate!=''){
			//如果有截止日期，则要补上当天最后的时间
			formdata.endDate = formData.endDate + '23:59:59';
		}
		$('#grid').datagrid('load',formdata);
	});
});
/**
*画图
*/
function showChart(data){
	$('#piechart').highcharts({
		chart:{
			plotBackgroudColor:null,
			plotBorderWidth:null,
			plotShadow:false,
			type:'pie'
		},
		title:{
			text:'销售统计'
		},
		tooltip:{
			pointFormat:'{series.name}: <b>{point.percentage:.1f}%</b>'
		},
		plotOptions:{
			pie:{
				allowPointSelect:true,
				cursor:'pointer',
				dataLabels:{
					enabled:true,
					format:'<b>{point.name}</b>:{point.percentage:.1f}%'
				},
				showInLegend:true
			}
		},
		series:[{
			name:'比例',
			colorByPoint:true,
			data:data
		}]
	})
}